[project]
name = "governance"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
vote_markdown = "python to_vote.py"

[dependencies]
python = ">=3.12.4,<3.13"
